const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generateTaxReceipt = (donorName, donationDetails) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    
    // Create receipts folder if not exists
    const receiptsDir = path.join(__dirname, '../uploads/receipts');
    if (!fs.existsSync(receiptsDir)) {
      fs.mkdirSync(receiptsDir, { recursive: true });
    }

    const fileName = `Receipt_${Date.now()}.pdf`;
    const filePath = path.join(receiptsDir, fileName);
    
    const writeStream = fs.createWriteStream(filePath);
    doc.pipe(writeStream);

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text('MealBridge', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('Official Tax Deduction Receipt', { align: 'center' });
    doc.moveDown(2);

    // Date and ID
    doc.fontSize(10).text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });
    doc.text(`Receipt ID: MB-${Math.floor(Math.random() * 1000000)}`, { align: 'right' });
    doc.moveDown(2);

    // Donor Info
    doc.fontSize(14).font('Helvetica-Bold').text('Donor Information:');
    doc.fontSize(12).font('Helvetica').text(`Name/Organization: ${donorName}`);
    doc.moveDown();

    // Donation Info
    doc.fontSize(14).font('Helvetica-Bold').text('Donation Details:');
    doc.fontSize(12).font('Helvetica');
    
    if (donationDetails.type === 'food') {
      doc.text(`Type: Food Donation`);
      doc.text(`Item: ${donationDetails.foodName}`);
      doc.text(`Quantity: ${donationDetails.quantity} ${donationDetails.unit}`);
      doc.text(`Helped: ~${donationDetails.peopleServed} people`);
    } else {
      doc.text(`Type: Financial Donation`);
      doc.text(`Amount: LKR ${donationDetails.amount}`);
      doc.text(`Campaign: ${donationDetails.campaignName}`);
    }
    
    doc.moveDown(2);
    
    // Footer / Legal text
    doc.fontSize(10).font('Helvetica-Oblique').text('This receipt is automatically generated by MealBridge and serves as an official acknowledgment of your charitable contribution. Keep this document for your tax records.', { align: 'center' });

    doc.end();

    writeStream.on('finish', () => {
      resolve(`/uploads/receipts/${fileName}`);
    });
    
    writeStream.on('error', (err) => {
      reject(err);
    });
  });
};

module.exports = { generateTaxReceipt };
